<?php

/*
 * You can find more configuration options in the documentation
 * in the doc/ folder or at <http://docs.phpmyadmin.net/>.
 */


 /*
  * Absolute uri of phpMyAdmin, can be leaved blank
  */
$cfg['PmaAbsoluteUri'] = '{{ PHPMYADMIN_CONFIG_ABSOLUTE_URI }}';

/*
 * Disable phpmyadmin version check
 */
$cfg['VersionCheck'] = false;

/*
 * Autogenerated value will be automatically added by phpmyadmin/container-start.sh
 */
$cfg['blowfish_secret'] = '{{ PHPMYADMIN_BLOWFISH_SECRET }}';


/*
 * Autogenerated servers will come here
 */
{{ PHPMYADMIN_SERVERS }}
