<?php

/*
 * You can find more configuration options in the documentation
 * in the doc/ folder or at <http://docs.phpmyadmin.net/>.
 */

/*
 * Autogenerated value will be automatically added by phpmyadmin/container-start.sh 
 */
$cfg['blowfish_secret'] = '';

/*
 * Autogenerated servers will come here
 */
